### ISSUE TITLE
No user found error

### ISSUE THREAD

**Issue by hitchnsmile** [ShellMonkeys/fb-messenger-es6#18] opened 2017-05-20 15:40 UTC
Getting then when sending message to user with quickReply buttons. Everything else works fine. Failed to understand why it's happening.

`
15:38:41 - error:  
{ message: '(#100) No matching user found',
  type: 'OAuthException',
  code: 100,
  error_subcode: 2018001,
  fbtrace_id: 'Fyvc4jsF4Qh' }
15:38:41 - error:  Error: (#100) No matching user found
    at /home/pastor/Developer/Up/coffeeBot/node_modules/fb-messenger-es6/src/client/client.js:51:23
    at process._tickDomainCallback (internal/process/next_tick.js:135:7)
(node:14949) UnhandledPromiseRejectionWarning: Unhandled promise rejection (rejection id: 3): Error: (#100) No matching user found
(node:14949) DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.
15:38:45 - error:  
{ message: '(#100) No matching user found',
  type: 'OAuthException',
  code: 100,
  error_subcode: 2018001,
  fbtrace_id: 'F0HVfiE4zFs' }
15:38:45 - error:  Error: (#100) No matching user found
    at /home/pastor/Developer/Up/coffeeBot/node_modules/fb-messenger-es6/src/client/client.js:51:23
    at process._tickDomainCallback (internal/process/next_tick.js:135:7)
(node:14949) UnhandledPromiseRejectionWarning: Unhandled promise rejection (rejection id: 6): Error: (#100) No matching user found
`

**Comment by davidrussell731** [comment] 2017-05-23 16:45
@hitchnsmile Can you please provide a code snippet of how you are constructing the message?

**Comment by hitchnsmile** [comment] 2017-05-23 20:29
@davidrussell731 
Of course. Here:
`getStarted: (chatID: number) => {
    facebook.sendMessage(new TextMessage(texts.messages.getStarted.text)
                            .addQuickReply(new TextQuickReply(texts.buttons.getStarted, 'GET_STARTED_PAYLOAD')), 
                            chatID)
  }`

**Comment by radTuti** [comment] 2017-05-29 18:14
@hitchnsmile `chatID` is the `USER_ID` right? It seems like you're trying to send the message to an invalid user. The error you get back is directly from Facebook.

What do you mean by everything else works fine?

**Comment by hitchnsmile** [comment] 2017-05-29 18:51
@radTuti That is correct.
I am not changing user_id and it gets sent either way after few errors.

Everything else: Generic templates, buttons and etc.
I get these errors only with quickReplies.

**Comment by radTuti** [comment] 2017-05-29 20:12
To narrow the root cause, can you try posting the message to FB directly?
```sh
curl -X POST -H "Content-Type: application/json" -d '{
  "recipient":{
    "id":chatID
  },
  "message":{
    "text":texts.messages.getStarted.text,
    "quick_replies":[
      {
        "content_type":"text",
        "title":texts.buttons.getStarted,
        "payload":"GET_STARTED_PAYLOAD"
      }
    ]
  }
}' "https://graph.facebook.com/v2.6/me/messages?access_token=PAGE_ACCESS_TOKEN"
```

**Comment by hitchnsmile** [comment] 2017-05-30 08:15
Curl was success.
Response:
`{"recipient_id":"1209488182492453","message_id":"mid.$cAADzaMpz351iia_VelcWGqM_YMG3"}`

Construction matches. Text and then replies.

**Comment by radTuti** [comment] 2017-05-31 13:10
Based on your last response; neither Facebook nor the lib seem to have a problem. Could it be possible that at some point when you invoke that you end up sending an invalid userId?

**Comment by hitchnsmile** [comment] 2017-05-31 13:13
@radTuti 
Hardly.
On user message, I'm taking userID from response.recipient_id and passing directly to the function which sends user quickReply options instantly

**Comment by radTuti** [comment] 2017-06-06 13:27
I am closing this issue as I haven't been able to replicate the issue and conclude that it might have something to do with how the user is accessed.

Using the lib:
```javascript
const messages = ProcessIncoming(req.body); //userID accessed using messages[PAGE_ID][0].sender
```

sans library
```javascript
//userID accessed using req.body.sender.id
```

**Closed by radTuti** 2017-06-06 13:27 UTC
